### ISSUE TITLE
Lepton L1 autoload failing on re-run

### ISSUE THREAD

**Issue by katzy687** [leptonsys/cloudshell-L1-coldfusion#1]
Resource already exists with 2 blades, but re-running autoload fails with error. Screenshot from resource manager and logs attached.
thanks!

[coldfusion_commands--01-Dec-2022--14-10-39.log](https://github.com/leptonsys/cloudshell-L1-coldfusion/files/10133121/coldfusion_commands--01-Dec-2022--14-10-39.log)
[coldfusion--01-Dec-2022--14-10-39.log](https://github.com/leptonsys/cloudshell-L1-coldfusion/files/10133124/coldfusion--01-Dec-2022--14-10-39.log)
![autoload-screenshot](https://user-images.githubusercontent.com/19604898/205076025-7e22d821-b9cb-44ea-9c00-fe9a50977170.png)

**Comment by katzy687** [comment]
fix sent over by team resolved issue. thanks!

**Comment by leptonsys** [comment]
Issue resolved in 1.3.5-EA
